### ISSUE TITLE
Some issues with the coding style

### ISSUE THREAD

**Issue by keyboard-slayer** [kohi-gnu-linux/unix-utils#4]
There are some issues with coding style it's not consistent.

Love from your kb-slayer :kissing_heart:

**Comment by d0p1s4m4** [comment]
true o/ thx

**Comment by d0p1s4m4** [comment]
fixed by [e403608](https://github.com/kohi-gnu/unix-utils/commit/e4036085dfae6c35fc342d9469db8c5c4971e4c2)
